version: '3.8'

services:
  nginx:
    image: nginx:1.21
    container_name: nginx
    volumes:
      - ./:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - my-network
    depends_on: 
      - flask
  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flask
    command: gunicorn --bind 0.0.0.0:8000 "flask_app.ajay:all()"
    volumes:
      - ./:/var/www
    networks: 
      my-network:
        aliases: 
          - flask-app

networks: 
  my-network:
